import 'package:flutter/material.dart';

Color primary = Colors.cyanAccent;
Color secondary = const Color.fromARGB(255, 125, 125, 127);
Color tColor = const Color.fromARGB(255, 8, 22, 44);
Color tColor2 = const Color.fromARGB(255, 238, 231, 219);
Color bgColor = const Color.fromARGB(255, 213, 213, 213);
Color bgColor2 = Colors.cyanAccent;
Color black = Colors.black;
Color white = Colors.white;
Color red = Colors.red;
Color orange = Colors.deepOrangeAccent;
Color amber = Colors.amber;
Color blue = Colors.blue;
Color cyan = Colors.cyanAccent;
Color green = const Color.fromARGB(255, 41, 255, 48);
Color transparent = Colors.transparent;
Color buttonColor = const Color.fromARGB(255, 142, 207, 250);
Color shimmerbaseColor = Colors.grey.shade300;
Color shimmerHighlightColor = Colors.grey.shade100;
